export default [
  {
    description:
      "Member of the week is a weekly rubric on our Facebook page. Each saturday, a member is selected based on their motivation level, their presence and their participation in our activities.",
    imgs: [
      "memberOfTheWeek/member1.webp",
      "memberOfTheWeek/member2.webp",
      "memberOfTheWeek/member3.webp",
      "memberOfTheWeek/member4.webp",
      "memberOfTheWeek/member5.webp",
      "memberOfTheWeek/member6.webp",
      "memberOfTheWeek/member7.webp",
      "memberOfTheWeek/member8.webp",
      "memberOfTheWeek/member9.webp",
      "memberOfTheWeek/member10.webp",
      "memberOfTheWeek/member11.webp",
      "memberOfTheWeek/member12.webp",
      "memberOfTheWeek/member13.webp",
      "memberOfTheWeek/member14.webp",
      "memberOfTheWeek/member15.webp",
      "memberOfTheWeek/member16.webp",
      "memberOfTheWeek/member17.webp",
      "memberOfTheWeek/member18.webp",
      "memberOfTheWeek/member19.webp",
      "memberOfTheWeek/member20.webp",
      "memberOfTheWeek/member21.webp",
    ],
  },
  {
    description:
      "One of the best things about RAS chapter is the connection we have with our members. Here are some pictures that translate the amazing atmosphere we have as a chapter.",
    imgs: [
      "familyGallery/family2.webp",
      "familyGallery/family3.webp",
      "familyGallery/family4.webp",
    ],
  },
  {
    description:
      "Gaining members trust and love is our key to sucess, that’s the reason why we held a team building. In ras chapter most of our work requires being in teams.",
    imgs: [
      "teambuilding/teambuilding1.webp",
      "teambuilding/teambuilding2.webp",
      "teambuilding/teambuilding3.webp",
      "teambuilding/teambuilding4.webp",
      "teambuilding/teambuilding5.webp",
      "teambuilding/teambuilding6.webp",
      "teambuilding/teambuilding7.webp",
      "teambuilding/teambuilding8.webp",
      "teambuilding/teambuilding9.webp",
      "teambuilding/teambuilding10.webp",
      "teambuilding/teambuilding11.webp",
      "teambuilding/teambuilding12.webp",
      "teambuilding/teambuilding13.webp",
      "teambuilding/teambuilding14.webp",
      "teambuilding/teambuilding15.webp",
      "teambuilding/teambuilding16.webp",
      "teambuilding/teambuilding17.webp",
      "teambuilding/teambuilding18.webp",
      "teambuilding/teambuilding19.webp",
      "teambuilding/teambuilding20.webp",
    ],
  },
];
